/**
 * University at Buffalo (SUNY Buffalo) Academic Programs
 * Authoritative catalog for the 2025-26 academic year sourced from
 * https://catalog.buffalo.edu (undergraduate majors) and
 * https://grad.buffalo.edu (graduate & professional programs).
 */

export interface Major {
  name: string;
  code?: string;
  school: string;
}

export const UB_UNDERGRADUATE_MAJORS: string[] = [
  'Accounting',
  'Acting',
  'Aerospace Engineering',
  'African American Studies',
  'AI and Geospatial Analytics',
  'AI and Language and Intercultural Competence',
  'AI and Language Technology',
  'AI and Logic and Ontology',
  'AI and Policy Analysis',
  'AI and Quantitative Economics',
  'AI and Responsible Communication',
  'American Studies',
  'Anthropology',
  'Architecture',
  'Art',
  'Art History',
  'Asian Studies',
  'Biochemistry',
  'Bioinformatics and Computational Biology',
  'Biological Sciences',
  'Biomedical Engineering',
  'Biomedical Sciences',
  'Biotechnology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Classics',
  'Cognitive Science',
  'Communication',
  'Computational Linguistics',
  'Computational Physics',
  'Computer Engineering',
  'Computer Science',
  'Criminology',
  'Dance',
  'Economics',
  'Electrical Engineering',
  'Engineering Physics',
  'Engineering Science',
  'English',
  'Environmental Design',
  'Environmental Engineering',
  'Environmental Science',
  'Environmental Studies',
  'Environmental Sustainability',
  'Exercise Science',
  'Film Studies',
  'French',
  'Geographic Information Science',
  'Geography',
  'Geological Sciences',
  'German',
  'Global Affairs',
  'Global Gender Studies',
  'Health and Human Services',
  'History',
  'Indigenous Studies',
  'Industrial Engineering',
  'Information Technology and Management',
  'International Studies',
  'International Trade',
  'Italian',
  'Jewish Studies',
  'Law',
  'Legal Studies',
  'Linguistics',
  'Material Science and Engineering',
  'Mathematics',
  'Mechanical Engineering',
  'Media Study',
  'Medical Laboratory Science',
  'Music',
  'Music Theatre',
  'Neuroscience',
  'Nuclear Medicine Technology',
  'Nursing',
  'Nursing RN to BS',
  'Nutrition Science',
  'Occupational Therapy',
  'Pharmaceutical Science',
  'Pharmacology and Toxicology',
  'Pharmacy',
  'Philosophy',
  'Philosophy, Politics and Economics',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Health',
  'Sociology',
  'Spanish',
  'Special Studies',
  'Speech and Hearing Science',
  'Statistics',
  'Theatre',
  'Theatre Design/Technology',
  'Urban and Public Policy Studies',
];

export const UB_GRADUATE_PROGRAMS: string[] = [
  'Accounting MS',
  'Adult/Gerontology Nurse Practitioner (Post-MS) DNP',
  'Adult/Gerontology Nurse Practitioner DNP',
  'Advanced Manufacturing Advanced Certificate',
  'Aerospace Engineering MS',
  'Aerospace Engineering PhD',
  'Affordable Housing Advanced Certificate',
  'American Studies MA',
  'American Studies PhD',
  'Anthropology and Law MA',
  'Anthropology BA/MA',
  'Anthropology MA',
  'Anthropology PhD',
  'Applied Biostatistics Advanced Certificate',
  'Applied Statistical Analysis Advanced Certificate',
  'Architecture MArch',
  'Architecture MArch/Business Administration MBA',
  'Architecture MArch/Urban Planning MUP',
  'Architecture MS',
  'Arts Management MA',
  'Assistive and Rehabilitative Technology Advanced Certificate',
  'Athletic Training MS',
  'Bilingual Education Advanced Certificate',
  'Biochemistry MS',
  'Biochemistry PhD',
  'Bioinformatics and Biostatistics MS',
  'Biological Sciences BA/MS',
  'Biological Sciences MA',
  'Biological Sciences MS',
  'Biological Sciences PhD',
  'Biology Education: Adolescence EdM',
  'Biomaterials MS',
  'Biomedical Engineering BS/MBA',
  'Biomedical Engineering MS',
  'Biomedical Engineering PhD',
  'Biomedical Informatics MS',
  'Biomedical Informatics MS/Pharmacy Practice PharmD',
  'Biomedical Informatics PhD',
  'Biostatistical Informatics Advanced Certificate',
  'Biostatistics MA',
  'Biostatistics PhD',
  'Biotechnology MS',
  'Bridge Engineering Advanced Certificate',
  'Business Administration MBA',
  'Business Administration BS/MBA',
  'Business Administration MBA/Pharmacy Practice PharmD',
  'Business Analytics MS',
  'Business Analytics Online MS',
  'Online Professional Business Administration MBA',
  'Cancer Sciences MS',
  'Cancer Sciences PhD',
  'Cellular and Molecular Physiology MS',
  'Chemical Engineering BS/MBA',
  'Chemical Engineering ME',
  'Chemical Engineering MS',
  'Chemical Engineering PhD',
  'Chemistry Education: Adolescence EdM',
  'Chemistry MS',
  'Chemistry PhD',
  'Child Health Nurse Practitioner (Post-MS) DNP',
  'Childhood Education (Grades 1-6) EdM',
  'Childhood Education with Bilingual Extension (Grades 1-6) EdM',
  'Civil Engineering MS',
  'Civil Engineering PhD',
  'Classics MA',
  'Classics PhD',
  'Clinical and Translational Therapeutics MS',
  'Clinical and Translational Therapeutics MS/Pharmacy Practice PharmD',
  'Clinical Nutrition MS',
  'Communication MA',
  'Communication PhD',
  'Communicative Disorders and Sciences AuD',
  'Communicative Disorders and Sciences MA',
  'Communicative Disorders and Sciences PhD',
  'Community Health and Health Behavior MS',
  'Community Health and Health Behavior PhD',
  'Comparative Literature MA',
  'Comparative Literature PhD',
  'Computational and Applied Mathematics MS',
  'Computational and Data Enabled Sciences PhD',
  'Computational Cell Biology, Anatomy and Pathology MS',
  'Computational Cell Biology, Anatomy and Pathology PhD',
  'Computational Earth Science MS',
  'Computational Linguistics MS',
  'Computer Science and Engineering MS',
  'Computer Science and Engineering PhD',
  'Computer Science BS/Master of Science MBA',
  'Computer Science Education EdM',
  'Contemporary Music Performance Advanced Certificate',
  'Contemporary Music Performance DMA',
  'Counseling/School Psychology PhD',
  'Criminal Law LLM',
  'Criminology MS',
  'Critical Museum Studies MA',
  'Cross-Border Legal Studies LLM',
  'Curriculum, Instruction and the Science of Learning PhD',
  'Cybersecurity Advanced Certificate',
  'Dance MFA',
  'Data Analytics for the Social Sciences Advanced Certificate',
  'Data Analytics in the Social Sciences MS',
  'Data Sciences and Applications MPS',
  'Dentistry DDS',
  'Drugs, Health and Society MA',
  'JSD (Doctor of Juridical Science)',
  'Early Childhood Education (Birth-Grade 2) EdM',
  'Early Childhood Education with Bilingual Extension (Birth-Grade 2) EdM',
  'Early Childhood/Childhood Education (Birth-Grade 6) EdM',
  'Earth Science Education: Adolescence EdM',
  'Econometrics and Quantitative Economics BA/MS',
  'Econometrics and Quantitative Economics MS',
  'Economics BA/MA',
  'Economics MA',
  'Economics PhD',
  'Education Studies EdM',
  'Educational Administration PhD',
  'Educational Culture, Policy and Society EdM',
  'Educational Culture, Policy and Society PhD',
  'Educational Data Science MS',
  'Educational Data Science PhD',
  'Educational Leadership EdD',
  'Electrical Engineering BS/MBA',
  'Electrical Engineering ME',
  'Electrical Engineering MS',
  'Electrical Engineering PhD',
  'Endodontics Advanced Certificate',
  'Engineering Education PhD',
  'Engineering Management ME',
  'Engineering Pedagogies and Practices Advanced Certificate',
  'Engineering Science (Artificial Intelligence) MS',
  'Engineering Science (Clean Energy) MS',
  'Engineering Science (Cybersecurity) MS',
  'Engineering Science (Data Science) MS',
  'Engineering Science (Engineering Sustainability) MS',
  'Engineering Science (Internet of Things) MS',
  'Engineering Science (Microelectronics and Semiconductor Engineering) MS',
  'Engineering Science (Quantum Science and Nanotechnology) MS',
  'Engineering Science (Robotics) MS',
  'English as a Second Language Advanced Certificate',
  'English BA/MA',
  'English Education Studies EdM',
  'English Education: Adolescence EdM',
  'English for Speakers of Other Languages EdM',
  'English MA',
  'English PhD',
  'Environmental and Water Resources Engineering MS',
  'Environmental and Water Resources Engineering PhD',
  'Environmental Health Sciences MS',
  'Epidemiology MS',
  'Epidemiology PhD',
  'Evolution, Ecology and Behavior MS',
  'Evolution, Ecology and Behavior PhD',
  'Exercise Science BS/Athletic Training MS',
  'Exercise Science BS/DPT',
  'Exercise Science BS/MS',
  'Exercise Science BS/Nutrition MS',
  'Exercise Science MS',
  'Exercise Science PhD',
  'Family Nurse Practitioner (Post-MS) DNP',
  'Family Nurse Practitioner Advanced Certificate',
  'Family Nurse Practitioner DNP',
  'Finance MS',
  'Fine Arts MFA',
  'French Education: Adolescence EdM',
  'French Language and Literature MA',
  'French Language and Literature PhD',
  'Genetic Counseling MS',
  'Genetics, Genomics and Bioinformatics MS',
  'Genetics, Genomics and Bioinformatics PhD',
  'Geographic Information Science MS',
  'Geography MA',
  'Geography MS',
  'Geography PhD',
  'Geological Sciences MS',
  'Geological Sciences PhD',
  'Global Affairs BA/MA',
  'Global Affairs MA',
  'Global Gender Studies MA',
  'Global Gender Studies PhD',
  'Higher Education and Student Affairs EdM',
  'Higher Education PhD',
  'Historic Preservation Advanced Certificate',
  'Historical Musicology and Music Theory PhD',
  'History Advanced Certificate',
  'History MA',
  'History PhD',
  'Humanities Interdisciplinary MA',
  'Humanities Interdisciplinary: Disability Studies MA',
  'Humanities Interdisciplinary: Film and Media Study MA',
  'Indigenous Studies MA',
  'Indigenous Studies PhD',
  'Industrial Engineering BS/MBA',
  'Industrial Engineering MS',
  'Industrial Engineering PhD',
  'Information and Library Science (Online) MS',
  'Information Science PhD',
  'International Dentist Program DDS',
  'International Development and Global Health MS',
  'International Educational Data Analysis Advanced Certificate',
  'International Trade MA',
  'Jewish Thought MA',
  'Language Education and Multilingualism PhD',
  'Latin Education: Adolescence EdM',
  'Law (Three Year) JD',
  'Law (Two Year) JD',
  'Law JD/MBA',
  'Law JD/MUP',
  'Law LLM',
  'Learning and Teaching in Social Contexts EdD',
  'Library and Information Science Advanced Certificate',
  'Linguistics MA',
  'Linguistics PhD',
  'Literacy Education Studies EdM',
  'Literacy Specialist EdM',
  'Literacy Teaching and Learning Advanced Certificate',
  'Management (Accounting) PhD',
  'Management (Finance) PhD',
  'Management (Management Science and Systems) PhD',
  'Management (Marketing) PhD',
  'Management (Operations Management and Strategy) PhD',
  'Management (Organization and Human Resources) PhD',
  'Management Information Systems MS',
  'Management MS',
  'Management Science STEM MBA',
  'Materials Design and Innovation MS',
  'Materials Design and Innovation PhD',
  'Math Education Studies EdM',
  'Mathematics BA/MA',
  'Mathematics Education: Adolescence EdM',
  'Mathematics MA',
  'Mathematics PhD',
  'MD-PhD Program',
  'Mechanical Engineering BS/MBA',
  'Mechanical Engineering MS',
  'Mechanical Engineering PhD',
  'Media Arts and Sciences MS',
  'Media Arts Production MFA',
  'Media Study (Critical Studies Concentration) BA/Arts Management MA',
  'Media Study (Production Concentration) BA/Arts Management MA',
  'Media Study PhD',
  'Medical Anatomy and Experimental Pathology MS',
  'Medical Physics MS',
  'Medical Physics PhD',
  'Medicinal Chemistry BS/MS',
  'Medicinal Chemistry MS',
  'Medicinal Chemistry PhD',
  'Medicine MD',
  'Mental Health Counseling MS',
  'Microbiology and Immunology MS',
  'Microbiology and Immunology PhD',
  'Music BA/Arts Management MA',
  'Music Composition MA',
  'Music Composition PhD',
  'Music Education Studies EdM',
  'Music Education, Initial/Professional EdM',
  'Music History MA',
  'Music Performance MM',
  'Music Theory MA',
  'Biomedical Sciences MS',
  'Neuroscience BS/MS',
  'Neuroscience MS',
  'Neuroscience PhD',
  'Nurse Anesthesia (Post-MS) DNP',
  'Nurse Anesthesia DNP',
  'Nursing PhD',
  'Nutrition MS',
  'Nutrition Science PhD',
  'Occupational Safety and Health Advanced Certificate',
  'Occupational Science BS/Occupational Therapy MS',
  'Oral and Maxillofacial Pathology Advanced Certificate',
  'Oral Biology PhD',
  'Oral Sciences MS',
  'Orthodontics MS/Advanced Certificate',
  'Pharmacometrics and Personalized Pharmacotherapy MS',
  'Pharmacometrics and Personalized Pharmacotherapy MS/Pharmacy Practice PharmD',
  'Pharmaceutical Sciences (PharmD cohort) MS',
  'Pharmaceutical Sciences (PharmD cohort) PhD',
  'Pharmaceutical Sciences BS/MS',
  'Pharmaceutical Sciences MS',
  'Pharmaceutical Sciences PhD',
  'Pharmacology and Toxicology BS/MS',
  'Pharmacology MS',
  'Pharmacology PhD',
  'Pharmacy Practice PharmD',
  'Pharmacy Practice PharmD/Public Health MPH',
  'PhD Programs in Biomedical Sciences PhD',
  'Philosophy MA',
  'Philosophy PhD',
  'Philosophy, Politics and Economics Advanced Certificate',
  'Physical Therapy DPT',
  'Physics Education: Adolescence EdM',
  'Physics MS',
  'Physics PhD',
  'Physiology PhD',
  'Political Science BA/MA',
  'Political Science MA',
  'Political Science PhD',
  'Prosthodontics Advanced Certificate',
  'Psychiatric/Mental Health Nurse Practitioner (Post-MS) DNP',
  'Psychiatric/Mental Health Nurse Practitioner Advanced Certificate',
  'Psychiatric/Mental Health Nurse Practitioner DNP',
  'Psychology MA',
  'Psychology: Behavioral Neuroscience PhD',
  'Psychology: Clinical PhD',
  'Psychology: Cognitive PhD',
  'Psychology: Social-Personality PhD',
  'Public Health (Addictions, In Person) MPH',
  'Public Health (Addictions, Online) MPH',
  'Public Health (Biostatistics) MPH',
  'Public Health (Community Health and Health Behavior) MPH',
  'Public Health (Environmental Health) MPH',
  'Public Health (Epidemiology, In Person) MPH',
  'Public Health (Epidemiology, Online) MPH',
  'Public Health (Health Services Administration, In Person) MPH',
  'Public Health (Health Services Administration, Online) MPH',
  'Public Health (Individualized, In Person) MPH',
  'Public Health (Individualized, Online) MPH',
  'Public Health (Online) Advanced Certificate',
  'Public Health (Seated) Advanced Certificate',
  'Public Health BS/Community Health and Health Behavior MS',
  'Public Health BS/Epidemiology MS',
  'Public Health BS/MPH',
  'Real Estate Development MS',
  'Rehabilitation Counseling Advanced Certificate',
  'Rehabilitation Counseling MS',
  'Rehabilitation Science MS',
  'Rehabilitation Science PhD',
  'School Building Leadership Advanced Certificate',
  'School Counseling Advanced Certificate',
  'School Counseling EdM',
  'School District Leadership Advanced Certificate',
  'School Librarianship MS',
  'School Psychology MA/Advanced Certificate',
  'Social Science-Interdisciplinary MS',
  'Social Studies Education: Adolescence EdM',
  'Social Welfare Online DSW',
  'Social Welfare PhD',
  'Social Work (Advanced Standing, Full Time) MSW',
  'Social Work (Advanced Standing, Part Time) MSW',
  'Social Work (Advanced Standing, Part Time, Online) MSW',
  'Social Work (Traditional, Full Time) MSW',
  'Social Work (Traditional, Part Time) MSW',
  'Social Work (Traditional, Part Time, Online) MSW',
  'Social Work BA/MSW',
  'Social Work JD/MSW',
  'Social Work MBA/MSW',
  'Social Work MPH/MSW',
  'Social Work MSW/Social Welfare PhD',
  'Sociology PhD',
  'Spanish Education: Adolescence EdM',
  'Spanish Language and Literature MA',
  'Spanish Language and Literature PhD',
  'Structural Biology MS',
  'Structural Biology PhD',
  'Studio Art (General Studio Concentration) BA/Arts Management MA',
  'Supply Chain Management MS',
  'Sustainability Advanced Certificate',
  'Sustainability Leadership MA',
  'Sustainable Transportation and Logistics MS',
  'Teaching English to Speakers of Other Languages EdM',
  'Temporomandibular Disorders and Orofacial Pain Advanced Certificate',
  'Theater BA/Arts Management MA',
  'Theatre Performance MA',
  'Theatre Performance PhD',
  'Urban and Regional Planning PhD',
  'Urban Planning JD/MUP',
  'Urban Planning MUP',
  "Women's Health Nurse Practitioner (Post-MS) DNP",
];

export const UB_MAJORS: Major[] = UB_UNDERGRADUATE_MAJORS.map((name) => ({
  name,
  school: 'Undergraduate Programs',
}));

/**
 * Get majors grouped by school
 */
export function getMajorsBySchool(): Record<string, Major[]> {
  return UB_MAJORS.reduce((acc, major) => {
    const school = major.school;
    if (!acc[school]) {
      acc[school] = [];
    }
    acc[school]!.push(major);
    return acc;
  }, {} as Record<string, Major[]>);
}

/**
 * Get all unique school names
 */
export function getSchoolNames(): string[] {
  return Array.from(new Set(UB_MAJORS.map((major) => major.school))).sort();
}

/**
 * Search majors by name
 */
export function searchMajors(query: string): Major[] {
  const lowercaseQuery = query.toLowerCase();
  return UB_MAJORS.filter(major =>
    major.name.toLowerCase().includes(lowercaseQuery)
  );
} 
