export interface InterestCategory {
  id: string;
  title: string;
  icon?: string;
  items: string[];
}

export const UB_INTEREST_CATEGORIES: InterestCategory[] = [
  {
    id: "academic_identity",
    title: "Academic identity (just say what you study)",
    icon: "📚",
    items: [
      "cs",
      "ai/ml",
      "data science",
      "math kid",
      "psych major",
      "bio on a pre-med lie",
      "chem struggle bus",
      "physics but failing",
      "meche",
      "civil",
      "ece",
      "architecture (no sleep)",
      "urban planning (maps are hot)",
      "soc",
      "media study",
      "english lit",
      "poli sci",
      "public health",
      "history nerd",
      "ed major",
      "pharm hostage",
      "nursing gang",
      "pre-law thoughts",
      "marketing slay",
      "finance bros",
      "accounting pain",
      "enviro sci",
      "astronomy dreamer",
    ],
  },
  {
    id: "study_style",
    title: "How you do school",
    icon: "🧠",
    items: [
      "8am victim",
      "no fridays gang",
      "t/th only life",
      "HUB sniping pro",
      "discussion ghost",
      "discussion overachiever",
      "study pod loyalist",
      "solo grinder",
      "lockwood fifth floor only",
      "silverman couch sleeper",
      "whispers + 3 tabs open",
      "finals crammer",
      "last-second submitter",
      "lecture napper",
      "rewatch gang",
      "tutor plug",
      "honors program regret",
      "canvas spammer",
      "course swapper",
    ],
  },
  {
    id: "housing_history",
    title: "Where you live / survived",
    icon: "🏠",
    items: [
      "ellicott maze certified",
      "greiner rich kid",
      "wilkeson 4th floor culture",
      "fargo squad",
      "spaulding ghost hours",
      "governors swamp unit",
      "goodyear sleeper agent",
      "clement basement regular",
      "south campus alone arc",
      "shared laundry fighter",
      "dorm microwave chef",
      "suite privileges",
      "common room convos",
      "ra energy",
      "lounge chair squatter",
      "my window doesn't close",
      "fire alarm at 3am veteran",
    ],
  },
  {
    id: "cold_weather",
    title: "Cold weather lore",
    icon: "❄️",
    items: [
      "ub never closes",
      "snow day denier",
      "wind tunnel pathfinder",
      "tunnel dweller",
      "boots for 6 months",
      "icy stairs fall memory",
      "blizzard class hero",
      "spring thaw believer",
      "gloves lost again",
      "finals with numb hands",
      "parka in class drip",
      "sledder behind c3",
      "hot chocolate walk survivor",
    ],
  },
  {
    id: "food_behaviors",
    title: "Food behavior (realistic)",
    icon: "🍴",
    items: [
      "tim's line again",
      "sizzles at midnight",
      "c3 roulette",
      "one world world tour",
      "meal plan regret",
      "dining hall critic",
      "ramen and vibes",
      "microwaved eggs (why)",
      "free food radar",
      "boba on the spine",
      "late night munchies",
      "brunch planner",
      "pizza logs apologist",
      "duff's > anchor (correct)",
      "fish fry fan",
      "vending machine hunter",
    ],
  },
  {
    id: "getting_around",
    title: "How you move",
    icon: "🧭",
    items: [
      "stampede veteran",
      "flint loop crowd",
      "metro rider",
      "loop runner",
      "parked at governors",
      "bus tracker refresh spammer",
      "spine longboarder menace",
      "biking to class in slush",
      "shuttle whisperer",
      "north-south commuter trauma",
      "carpool with strangers",
      "walked to south campus once",
    ],
  },
  {
    id: "campus_events",
    title: "Chaos / events / culture",
    icon: "🎉",
    items: [
      "oozefest bruises",
      "human ub photo (somewhere)",
      "welcome week overdid it",
      "spring fest in the mud",
      "international fiesta stan",
      "painting the bull at 2am",
      "club fair sticker hoarder",
      "midnight breakfast squad",
      "late night ub ice skating",
      "watched homecoming game for 5 mins",
      "slept through orientation",
      "made 3 friends at club tabling",
    ],
  },
  {
    id: "micro_lore",
    title: "Micro-lore & reddit lore",
    icon: "🗺️",
    items: [
      "the knox 20 thing",
      "human meat chalking knower",
      "capen echo spot",
      "hayes hall ghost hunt",
      "c3 potato tracker",
      "1capen line trauma",
      "clemens top floor existential",
      "ellicott tunnel speedrun",
      "stampede sardine hours",
      "tims in su line at max capacity",
      "stairwell selfies",
      "hub meltdown screenshot",
      "lost in baldwin",
      "capen piano player fan",
      "paintball bull pics",
    ],
  },
  {
    id: "media_and_content",
    title: "Media & content consumption",
    icon: "💻",
    items: [
      "reddit all day",
      "discord during lecture",
      "tiktok but only food",
      "instagram 2nd account",
      "canvas refresh spammer",
      "zoom link finder",
      "spotify sharer",
      "photodump curator",
      "groupchat lurker",
      "posted on bereal late",
      "linkedin updates once",
      "shared wrong doc link again",
    ],
  },
  {
    id: "gaming_and_game_night",
    title: "Dorm gamers & game night folks",
    icon: "🎮",
    items: [
      "league until 3am",
      "valorant but angry",
      "smash tourney tryhard",
      "dorm mario kart lobby",
      "d&d on whiteboard",
      "board game wednesday",
      "chess with strangers",
      "uno bloodbath",
      "jackbox hoster",
      "minecraft realm hoarder",
      "modded skyrim phase",
      "among us in 2020 nostalgia",
    ],
  },
  {
    id: "creative_scene",
    title: "Artsy / creative people",
    icon: "🧵",
    items: [
      "poster designer",
      "flyer maker with canva",
      "theatre crew energy",
      "dance team legs hurt",
      "choir kid",
      "music major stress",
      "open mic reader",
      "zine table tabler",
      "cosplay mid-build",
      "riso print smell enjoyer",
      "beat maker",
      "acapella warmups at 9am",
      "nails and braids crew",
    ],
  },
  {
    id: "builders_and_hustle",
    title: "Build / hustle / tools",
    icon: "🛠️",
    items: [
      "side project graveyard",
      "github contributor (lowkey)",
      "portfolio not finished",
      "resume panic edit",
      "figma experimenter",
      "cs club sometimes",
      "prompt craft nerd",
      "soldering for fun",
      "startup idea 12",
      "job app spammer",
      "worked 3 jobs",
      "on-campus job lifer",
      "tutoring as a side hustle",
      "canvas calendar warrior",
      "engineering memes only",
    ],
  },
  {
    id: "social_energy",
    title: "Social behavior",
    icon: "🧍",
    items: [
      "house show fan",
      "party on winspear",
      "trivia at mr goodbar",
      "chip strip once a semester",
      "movie nights in dorm lounge",
      "karaoke half sober",
      "darty survivor",
      "stayed in tonight",
      "people-watching in capen",
      "brunch with 1 friend",
      "met on hinge",
      "passed someone you ghosted",
      "joined club for vibes",
      "made groupchat and muted it",
    ],
  },
  {
    id: "health_wellness",
    title: "Health & wellness",
    icon: "🧘",
    items: [
      "gym twice a week (ish)",
      "yoga on tuesdays",
      "spin class dropper",
      "walking the spine for cardio",
      "meditation app opened once",
      "therapy squad",
      "counselor referral chain",
      "sleep schedule destroyed",
      "self-care spreadsheet",
      "hydration but not really",
      "journaling in google docs",
      "10 alarms and still late",
    ],
  },
  {
    id: "identity_background",
    title: "Identity / background",
    icon: "💬",
    items: [
      "first-gen",
      "transferred in",
      "international student",
      "commuter life",
      "lives off campus",
      "bilingual",
      "lives with siblings",
      "roommate history",
      "lgbtq+ at ub",
      "cultural org active",
      "faith-based org",
      "women in stem energy",
      "men's group",
      "grad student energy",
      "eop/trio/honors",
    ],
  },
];
