#!/usr/bin/env node
/**
 * Build script for HIVE Design Tokens
 * Generates CSS custom properties from TypeScript design tokens
 */

const fs = require('fs');
const path = require('path');

// Import the compiled generator from dist (using PRD-aligned generator)
const { generateCompleteCSS } = require('../dist/css-variables-generator');

// Define output paths
const outputPath = path.join(__dirname, '../hive-tokens-generated.css');
const sourceOutputPath = path.join(__dirname, '../src/hive-tokens-generated.css');

try {
  console.log('🎨 Generating HIVE design tokens CSS...');

  // Generate complete CSS (variables + utilities)
  const css = generateCompleteCSS();

  // Add header comment
  const finalCSS = `/**
 * HIVE Design Tokens - Generated CSS Custom Properties
 * DO NOT EDIT THIS FILE DIRECTLY
 * Generated from packages/tokens/src/** (PRD-aligned)
 *
 * To regenerate: pnpm --filter @hive/tokens build
 */

${css}
`;

  // Write to both locations
  fs.writeFileSync(outputPath, finalCSS, 'utf-8');
  fs.writeFileSync(sourceOutputPath, finalCSS, 'utf-8');

  // Count variables for reporting
  const varCount = (css.match(/--hive-/g) || []).length;
  const lineCount = css.split('\n').length;

  console.log(`✅ Generated ${varCount} CSS custom properties`);
  console.log(`📊 Generated ${lineCount} lines of CSS`);
  console.log(`📝 Output: ${outputPath}`);
  console.log(`📝 Mirrored: ${sourceOutputPath}`);
  console.log('🎉 Design tokens built successfully!');

} catch (error) {
  console.error('❌ Error generating CSS tokens:', error.message);
  console.error(error.stack);
  process.exit(1);
}
